#!/bin/bash

# TODO: If this script isn't run from the util directory still make it work
# TODO: Accept the -f flag

cd ./cbb_scraper
go build .
cd ..
python3 get_data.py -f
./cbb_scraper/cbb_scraper
